apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: heavy-runtime
spec:
  resourceRef:
    apiGroup: ""
    kind: Pod
  
  selector:
    matchLabels:
      duration: heavy
    
    matchExpressions:
      - key: .status.phase 
        operator: In
        values:
        - Running

  delay:
    durationMilliseconds: 27000
    jitterDurationMilliseconds: 50000
    
  next:
    delete: true