apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: light-runtime
spec:
  resourceRef:
    apiGroup: ""
    kind: Pod
  
  selector:
    matchLabels:
      duration: light
    
    matchExpressions:
      - key: .status.phase 
        operator: In
        values:
        - Running

  delay:
    durationMilliseconds: 5000
    jitterDurationMilliseconds: 10000
      
  next:
    delete: true