apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: medium-runtime
spec:
  resourceRef:
    apiGroup: ""
    kind: Pod
  
  selector:
    matchLabels:
      duration: medium
    
    matchExpressions:
      - key: .status.phase 
        operator: In
        values:
        - Running

  delay:
    durationMilliseconds: 12000
    jitterDurationMilliseconds: 25000
      
  next:
    delete: true