apiVersion: gpu.com/v1
kind: Specification
metadata:
  name: example
  namespace: default
spec:
  gpus:
  - mig-enabled: false
    available: 10
  - mig-enabled: true
    mig-slices:
    - size: 4
      mem: 20
      available: 10
    - size: 3
      mem: 15
      available: 10