apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: specifications.gpu.com
spec:
  group: gpu.com
  scope: Namespaced
  names:
    plural: specifications
    singular: specification
    kind: Specification
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object

            properties:
              gpus:
                type: array
                items:
                  type: object
                  properties:
                    gpuName:
                      type: string
                    usage:
                      type: int64
                    mig-enabled:
                      type: bool

                    mig-instances:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          size:
                            type: int64
                          position:
                            type: int64
                          usage:
                            type: int64
