apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: specifications.gpu.com
spec:
  group: gpu.com
  scope: Namespaced
  names:
    plural: specifications
    singular: specification
    kind: Specification
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object

            properties:
              gpus:
                type: array
                items:
                  type: object
                  properties:
                    available:
                      type: integer # sobre 10
                    mig-enabled:
                      type: boolean
                      
                    mig-slices:
                      type: array
                      items:
                        type: object
                        properties:
                          size:
                            type: integer
                          position:
                            type: integer
                          available:
                            type: integer # sobre 10
                          mem:
                            type: integer
