apiVersion: gpu.com/v1
kind: Specification
metadata:
  name: example
  namespace: default
spec:
  gpus:
  - available: 10
  - mig-slices:
    - size: 4
      position: 0
      available: 10
    - size: 3
      position: 4
      available: 10