topology:
  nodePools:
    pool0:
      gpuProduct: NVIDIA-L4-24GB
      gpuMemory: 16000
      gpuCount: 2

    pool1:
      gpuProduct: NVIDIA-H100-PCIe-80GB
      gpuMemory: 80000
      otherDevices:
        - name: "gpu0-2g.20gb"
          count: 2
        - name: "gpu0-3g.40gb"
          count: 1


  nodePoolLabelKey: "run.ai/simulated-gpu-node-pool"
  migStrategy: "mixed"